version: "3.1"

services:
  postgres:
    container_name: postgres_reeact
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: reeactcafe
    ports:
      - 5432:5432
